"""Docstring-based API reference generator and documentation checker.

This is the "build" half of the repository's four-layer documentation
structure (quick start in the READMEs -> concepts -> guides -> API reference):

* ``build`` regenerates ``docs/api/<component>.md`` from the docstrings of each
  component's public modules (pure ``ast``: nothing is imported, so the build
  is hermetic and works offline with the standard library only);
* ``verify`` checks, without writing, that the committed API pages are fresh
  (byte-identical to what the generator produces) and that every internal
  markdown link in the repository resolves to an existing file.

The same checks run as unit tests (``tests/test_docbuild.py``) under
``make test`` and are repeated by the CI documentation job (structure tests +
this build/link check).

Usage:
    python3 tests/docbuild.py build     # regenerate docs/api/*.md
    python3 tests/docbuild.py verify    # freshness + links; exit 1 on drift
"""
from __future__ import annotations

import ast
import re
import sys
import urllib.parse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
API_DIR = ROOT / "docs" / "api"

# component name (docs/api slug and directory name) -> public modules.
# Modules are listed explicitly on purpose: an added public module must be
# consciously exposed in the API reference (and the freshness check then keeps
# it there).
MANIFEST: dict[str, tuple[str, ...]] = {
    "northstar-run-contract": ("contract", "binding", "adapter", "audit"),
    "northstar-host": ("authorization", "workspace", "host_audit"),
    "northstar-durable-run": (
        "durable_contract",
        "event_store",
        "action_gateway",
        "runner",
        "verifier",
        "trace_metrics",
        "evaluation",
        "durable_audit",
    ),
    "northstar-agent-interop": (
        "interop_contract",
        "handoff",
        "interop_adapter",
        "canary",
        "process_adapter",
        "process_backend",
    ),
    "northstar-codex-sidecar": ("sidecar", "transport", "service", "sidecar_socket"),
    "northstar-agent-runtime": (
        "agents",
        "agent_files",
        "budget",
        "cli",
        "compaction",
        "doctor",
        "frontmatter",
        "hooks",
        "loop",
        "mcp_client",
        "permissions",
        "policy_file",
        "sessions",
        "session_view",
        "sidecar_client",
        "skills",
        "tracing",
        "audit_export",
        "tools.__init__",
        "providers.base",
        "providers.anthropic",
        "providers.scripted",
    ),
}

GENERATED_HEADER = (
    "<!-- GENERATED by tests/docbuild.py - do not edit; run `python3 tests/docbuild.py build` -->"
)

_SELF_ARGUMENTS = {"self", "cls", "mcs"}
_LINK_RE = re.compile(r"(?<!!)\[[^\]]*\]\(([^)]+)\)")
_FENCE_RE = re.compile(r"^(`{3,}|~{3,})")

# Relative-to-README link anchors each component README must offer (see
# tests/test_docbuild.py): one concepts page, one guides page, its own API page.
CONCEPTS_LINK = "../../docs/concepts/governance.md"
GUIDES_LINK = "../../docs/guides/packaging-and-ci.md"


def _summary(docstring: str | None, *, cap: int = 300) -> str:
    """First paragraph of a cleaned docstring, truncated for a reference page."""
    if not docstring:
        return ""
    text = docstring.strip().split("\n\n", 1)[0].replace("\n", " ")
    text = re.sub(r"\s+", " ", text).strip()
    if len(text) > cap:
        text = text[: cap - 1].rstrip() + "\u2026"
    return text


def _signature(node: ast.FunctionDef | ast.AsyncFunctionDef | ast.ClassDef) -> str:
    """Render a callable's parameter list from the AST (annotations included)."""
    if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
        args = node.args
        # Drop the leading self/cls so method signatures read naturally.
        positionals = list(args.posonlyargs) + list(args.args)
        dropped = positionals and positionals[0].arg in _SELF_ARGUMENTS
        if dropped:
            rebuilt = ast.arguments(
                posonlyargs=args.posonlyargs[1:] if args.posonlyargs else [],
                args=args.args[1:] if not args.posonlyargs else args.args,
                vararg=args.vararg,
                kwonlyargs=args.kwonlyargs,
                kw_defaults=args.kw_defaults,
                kwarg=args.kwarg,
                defaults=args.defaults,
            )
            args = rebuilt
        try:
            params = ast.unparse(args)
        except Exception:  # pragma: no cover - malformed AST edge
            params = "\u2026"
        prefix = "async " if isinstance(node, ast.AsyncFunctionDef) else ""
        return f"{prefix}{node.name}({params})"
    return f"{node.name}()"


def _module_id(component: str, module: str) -> str:
    return module.replace(".__init__", "").replace("/", ".")


def _render_module(component: str, module: str, source: Path) -> list[str]:
    tree = ast.parse(source.read_text(encoding="utf-8"), filename=str(source))
    lines: list[str] = []
    heading = _module_id(component, module)
    lines.append(f"### `{heading}`")
    lines.append("")
    lines.append(f"Source: `{source.relative_to(ROOT).as_posix()}`")
    lines.append("")
    doc = ast.get_docstring(tree, clean=True)
    if doc:
        lines.append(_summary(doc))
        lines.append("")
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and not node.name.startswith("_"):
            lines.append(f"#### `{_signature(node)}`")
            summary = _summary(ast.get_docstring(node, clean=True))
            if summary:
                lines.append("")
                lines.append(summary)
            lines.append("")
        elif isinstance(node, ast.ClassDef) and not node.name.startswith("_"):
            lines.append(f"#### `{node.name}`")
            summary = _summary(ast.get_docstring(node, clean=True))
            if summary:
                lines.append("")
                lines.append(summary)
            lines.append("")
            for member in node.body:
                if isinstance(member, (ast.FunctionDef, ast.AsyncFunctionDef)) and not member.name.startswith("_"):
                    lines.append(f"- `{_signature(member)}`")
                    member_summary = _summary(ast.get_docstring(member, clean=True), cap=200)
                    if member_summary:
                        lines.append(f"  - {member_summary}")
    return lines


def render_page(component: str) -> str:
    """Render the full API reference page for one component."""
    component_dir = ROOT / "components" / component
    readme = component_dir / "README.md"
    lines = [
        f"# {component} - API reference",
        "",
        GENERATED_HEADER,
        "",
        "Docstring-generated reference over the component's public modules "
        "(``ast``-extracted; nothing is imported, so this builds offline with the "
        "standard library). The README is the quick start and integration guide:",
        "",
        f"- [README (quick start)](../../components/{component}/README.md)",
        f"- [Concepts](../../docs/concepts/governance.md) and "
        f"[guides](../../docs/guides/governed-run-cookbook.md)",
        "",
        "## Modules",
        "",
    ]
    for module in MANIFEST[component]:
        source = component_dir / Path(*module.split(".")).with_suffix(".py")
        if module.endswith(".__init__"):
            source = component_dir / Path(module.removesuffix(".__init__")) / "__init__.py"
        if not source.is_file():
            raise FileNotFoundError(f"manifest module not found: {source}")
        lines += _render_module(component, module, source)
    # Drop trailing blank lines, keep exactly one final newline.
    while lines and lines[-1] == "":
        lines.pop()
    return "\n".join(lines) + "\n"


def build_all() -> dict[str, str]:
    """Return {component: page text} for every component in the manifest."""
    return {component: render_page(component) for component in MANIFEST}


def write_all() -> list[Path]:
    """Regenerate docs/api/*.md on disk; returns the written paths."""
    written: list[Path] = []
    for component, text in build_all().items():
        path = API_DIR / f"{component}.md"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        written.append(path)
    return written


def stale_pages() -> list[str]:
    """Names of committed API pages that differ from a fresh generation."""
    stale: list[str] = []
    for component, text in build_all().items():
        path = API_DIR / f"{component}.md"
        if not path.is_file() or path.read_text(encoding="utf-8") != text:
            stale.append(component)
    return stale


def markdown_files() -> list[Path]:
    return sorted(
        path
        for path in ROOT.rglob("*.md")
        if ".git" not in path.parts and "node_modules" not in path.parts
    )


def broken_links() -> list[str]:
    """Every internal markdown link that does not resolve to an existing path.

    Code fences are skipped; external URLs, fragment-only anchors and mailto:
    links are not checked. Reported as ``<file>: <target>``.
    """
    broken: list[str] = []
    for path in markdown_files():
        in_fence = False
        for number, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
            if _FENCE_RE.match(raw):
                in_fence = not in_fence
                continue
            if in_fence:
                continue
            for match in _LINK_RE.finditer(raw):
                target = match.group(1).strip().strip("<>").strip()
                if not target or target.startswith(("#", "http://", "https://", "mailto:", "//")):
                    continue
                bare = urllib.parse.unquote(target.split("#", 1)[0]).strip()
                if not bare:
                    continue
                resolved = (path.parent / bare).resolve()
                if not resolved.exists():
                    broken.append(f"{path.relative_to(ROOT).as_posix()}:{number}: {target}")
    return broken


def verify() -> int:
    """Freshness + links check used by CI and by the unit tests."""
    stale = stale_pages()
    links = broken_links()
    print(f"api pages: {len(MANIFEST)} components, modules "
          f"{sum(len(m) for m in MANIFEST.values())}")
    if stale:
        print("stale (run `python3 tests/docbuild.py build`):")
        for name in stale:
            print(f"  - docs/api/{name}.md")
    print(f"markdown files checked: {len(markdown_files())}")
    if links:
        print("broken links:")
        for entry in links:
            print(f"  - {entry}")
    if stale or links:
        print("documentation build FAILED")
        return 1
    print("documentation build OK (fresh + links resolve)")
    return 0


def main(argv: list[str] | None = None) -> int:
    args = list(argv if argv is not None else sys.argv[1:])
    if not args or args[0] not in {"build", "verify"}:
        print(__doc__)
        return 2
    if args[0] == "build":
        for path in write_all():
            print(f"wrote {path.relative_to(ROOT).as_posix()}")
        return 0
    return verify()


if __name__ == "__main__":
    raise SystemExit(main())
