"""AI counterfactual: declared what-if decision ledger, Simulated.

Research note: counterfactual explanations ("what minimal change would
flip this decision?") are a staple of the interpretability literature,
but a *booked* counterfactual never proves the model would have
behaved that way - the perturbation is generated by the host under a
declared method, the originals never enter the ledger, and every
verdict is booked as data. What matters here is the *decision ledger*:
which systems had which declared counterfactual generations, under
which pinned generation-method vocabulary, with what declared
plausibility verdict and evidence digest pin - defensible
bookkeeping, never proof of real model behavior.

This module owns the counterfactual -> verify lifecycle:

* **counterfactual()** - book one declared counterfactual pair for a
  system (minted ``cfn-N`` ids; pinned 8-term generation-method
  vocabulary and pinned plausibility verdicts ``plausible`` /
  ``implausible`` / ``inconclusive`` / ``unverifiable`` /
  ``not-assessed``). The first counterfactual registers its system.
  Raw inputs, outputs, perturbations, feature vectors, and attribution
  internals never enter records - digest pins only.
* **verify()** - pure read: re-derive the digest pin of any
  counterfactual record; verdict ``verified`` / ``tampered`` booked as
  data (tamper reported, never raised).
* **evaluate()** - pure read: per-system plausibility tallies and a
  ledger-rule posture derived as data; ``integrity_ok`` re-derives
  every in-scope digest pin as data.
* **retire()** - terminal retirement of a system id; ids are never
  recycled.

Distinct-layer rationale: ``counterfactual_explanation_probes.py``
owns the probe corpus plus deterministic quality gates and the
simulatability harness for explanation *surfaces* (attacker-facing
quality measurement); ``ai_explainability.py`` owns system-level
explanation *provisions* (``counterfactual`` is one of its pinned
explanation kinds, but only at the provision level) - this module is
the dedicated counterfactual *generation* ledger none of them own:
original decision -> declared minimal-change alternative -> declared
plausibility verdict, all booked as data.

House style: frozen dataclasses, caller-supplied strictly-increasing
int seqs (claim-then-burn: failed mutations consume their seq and book
an ``ai-counterfactual.rejected`` row; rewinds raise bare without
consuming), no wall-clock, RLock guarding, fail-closed taxonomy,
stdlib-only with the standard ``canonical_json`` try/except fallback,
``sha256:`` digest pins, and ``audit.ndjson/1`` events.

Honest scope: this module generates no counterfactuals, probes no
models, and proves nothing about real behavior. A booked ``plausible``
verdict means "the host declared it", never "the model would really
flip". Raw inputs, outputs, perturbations, features, attributions,
and model internals never enter records or cross the audit boundary -
digest pins only.
"""

from __future__ import annotations

import hashlib
import threading
from dataclasses import dataclass
from typing import Any, Dict, List, Tuple

try:
    from canonical_json import jcs_dumps as _jcs_dumps, jcs_sha256_hex as _jcs_hash  # type: ignore
except Exception:  # pragma: no cover - fallback when canonical_json is absent

    def _jcs_dumps(obj: Any) -> bytes:  # type: ignore
        import json

        return json.dumps(obj, sort_keys=True, separators=(",", ":")).encode("utf-8")

    def _jcs_hash(obj: Any) -> str:  # type: ignore
        return "sha256:" + hashlib.sha256(_jcs_dumps(obj)).hexdigest()


#: Module version pin.
AI_COUNTERFACTUAL_VERSION = "ai-counterfactual.v1"

#: Schema pin for records produced by this module.
SCHEMA_PIN = "northstar.ai-counterfactual.v1"

#: Pinned counterfactual-generation-method vocabulary (the generation
#: methods this ledger tracks; booked as data, never proof of method).
GENERATION_KINDS = (
    "input-perturbation",
    "instance-retrieval",
    "optimization-search",
    "rule-template",
    "generative-rewrite",
    "boundary-sampling",
    "importance-flip",
    "human-authored",
)

#: Pinned plausibility-verdict vocabulary (booked as data, never proof).
VERDICTS = (
    "plausible",
    "implausible",
    "inconclusive",
    "unverifiable",
    "not-assessed",
)

#: Pinned retirement-reason vocabulary.
RETIRE_REASONS = (
    "manual",
    "superseded",
    "decommissioned",
    "false-start",
)

#: Audit kinds emitted by this module.
AUDIT_KINDS = (
    "counterfactualled",
    "retired",
    "rejected",
)

#: Keys that may never appear raw in an audit row. Pinned vocabulary
#: values (generation_kind, verdict, reason) and declared scalars
#: (severity) remain emittable as declared data; everything below is
#: raw material that travels as a digest pin only.
_BANNED_AUDIT_KEYS = frozenset(
    {
        "counterfactual_text",
        "counterfactuals",
        "counterfactual",
        "original_input",
        "original_inputs",
        "original_output",
        "original_outputs",
        "perturbed_input",
        "perturbed_inputs",
        "perturbation",
        "perturbations",
        "minimal_change",
        "edits",
        "edit",
        "feature",
        "features",
        "feature_vector",
        "feature_vectors",
        "attribution",
        "attributions",
        "saliency",
        "saliency_map",
        "shap_values",
        "lime",
        "integrated_gradients",
        "explanation",
        "explanations",
        "input_text",
        "output_text",
        "inputs",
        "input",
        "outputs",
        "output",
        "label",
        "labels",
        "prediction",
        "predictions",
        "decision",
        "decisions",
        "decision_rationale",
        "prompt",
        "prompts",
        "model_output",
        "model_outputs",
        "transcript",
        "transcripts",
        "weights",
        "model_weights",
        "parameters",
        "params",
        "score",
        "scores",
        "traces",
        "trace",
        "evidence",
        "result",
        "results",
        "raw",
        "secret",
        "key",
        "content",
        "text",
        "note",
        "notes",
        "detail",
        "details",
        "description",
        "report",
    }
)


# ---------------------------------------------------------------------------
# Errors
# ---------------------------------------------------------------------------


class AICounterfactualError(Exception):
    """Base error for AI-counterfactual ledger misuse."""


class BadIdError(AICounterfactualError):
    """Malformed system or counterfactual id."""


class RetiredSystemError(AICounterfactualError):
    """System id already retired; never recycled."""


class UnknownSystemError(AICounterfactualError):
    """System not registered."""


class BadGenerationKindError(AICounterfactualError):
    """Unknown counterfactual generation kind."""


class BadVerdictError(AICounterfactualError):
    """Unknown plausibility verdict."""


class BadSeverityError(AICounterfactualError):
    """Severity is not a host-reported int in [0, 100]."""


class BadDigestError(AICounterfactualError):
    """Malformed sha256: digest pin."""


class UnknownCounterfactualError(AICounterfactualError):
    """Counterfactual id not booked (or record id unknown)."""


class BadReasonError(AICounterfactualError):
    """Unknown retirement reason."""


class SeqOrderError(AICounterfactualError):
    """Seq is not a strictly increasing positive int."""


class AuditKindError(AICounterfactualError):
    """Unknown audit kind, or banned raw key in audit details."""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _require_id(value: Any, field_name: str) -> str:
    if not isinstance(value, str) or not value or len(value) > 128:
        raise BadIdError(f"{field_name} must be a non-empty str <= 128 chars")
    return value


def _require_severity(value: Any, field_name: str) -> int:
    if isinstance(value, bool) or not isinstance(value, int):
        raise BadSeverityError(f"{field_name} must be an int in [0, 100], not bool")
    if value < 0 or value > 100:
        raise BadSeverityError(f"{field_name} must be an int in [0, 100]")
    return value


def _require_digest(pin: Any, field_name: str) -> str:
    if not isinstance(pin, str) or not pin.startswith("sha256:"):
        raise BadDigestError(f"{field_name} must be a 'sha256:' pin")
    hexpart = pin[7:]
    if len(hexpart) != 64 or any(c not in "0123456789abcdef" for c in hexpart):
        raise BadDigestError(f"{field_name} must be a 64-hex sha256 pin")
    return pin


def _digest_pin(payload: Dict[str, Any]) -> str:
    raw = _jcs_hash(payload)
    hexpart = raw[7:] if raw.startswith("sha256:") else raw
    return "sha256:" + hexpart


# ---------------------------------------------------------------------------
# Records (all frozen)
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class CounterfactualRecord:
    counterfactual_id: str
    system_id: str
    generation_kind: str
    verdict: str
    severity: int
    counterfactual_digest: str
    digest: str

    def as_dict(self) -> Dict[str, Any]:
        return {
            "schema": SCHEMA_PIN,
            "counterfactual_id": self.counterfactual_id,
            "system_id": self.system_id,
            "generation_kind": self.generation_kind,
            "verdict": self.verdict,
            "severity": self.severity,
            "counterfactual_digest": self.counterfactual_digest,
            "digest": self.digest,
        }

    def verify(self) -> bool:
        return self.digest == _digest_pin(
            {
                "schema": SCHEMA_PIN,
                "counterfactual_id": self.counterfactual_id,
                "system_id": self.system_id,
                "generation_kind": self.generation_kind,
                "verdict": self.verdict,
                "severity": self.severity,
                "counterfactual_digest": self.counterfactual_digest,
            }
        )


@dataclass(frozen=True)
class RetireRecord:
    system_id: str
    reason: str
    digest: str

    def as_dict(self) -> Dict[str, Any]:
        return {
            "schema": SCHEMA_PIN,
            "system_id": self.system_id,
            "reason": self.reason,
            "digest": self.digest,
        }

    def verify(self) -> bool:
        return self.digest == _digest_pin(
            {
                "schema": SCHEMA_PIN,
                "system_id": self.system_id,
                "reason": self.reason,
            }
        )


@dataclass(frozen=True)
class VerificationReport:
    record_id: str
    record_kind: str
    verdict: str
    digest: str

    def as_dict(self) -> Dict[str, Any]:
        return {
            "schema": SCHEMA_PIN,
            "record_id": self.record_id,
            "record_kind": self.record_kind,
            "verdict": self.verdict,
            "digest": self.digest,
        }

    def verify(self) -> bool:
        return self.digest == _digest_pin(
            {
                "schema": SCHEMA_PIN,
                "record_id": self.record_id,
                "record_kind": self.record_kind,
                "verdict": self.verdict,
            }
        )


@dataclass(frozen=True)
class EvaluationReport:
    system_id: str
    n_counterfactuals: int
    n_plausible: int
    n_implausible: int
    n_inconclusive: int
    n_unverifiable: int
    n_not_assessed: int
    posture: str
    integrity_ok: bool
    digest: str

    def as_dict(self) -> Dict[str, Any]:
        return {
            "schema": SCHEMA_PIN,
            "system_id": self.system_id,
            "n_counterfactuals": self.n_counterfactuals,
            "n_plausible": self.n_plausible,
            "n_implausible": self.n_implausible,
            "n_inconclusive": self.n_inconclusive,
            "n_unverifiable": self.n_unverifiable,
            "n_not_assessed": self.n_not_assessed,
            "posture": self.posture,
            "integrity_ok": self.integrity_ok,
            "digest": self.digest,
        }

    def verify(self) -> bool:
        return self.digest == _digest_pin(
            {
                "schema": SCHEMA_PIN,
                "system_id": self.system_id,
                "n_counterfactuals": self.n_counterfactuals,
                "n_plausible": self.n_plausible,
                "n_implausible": self.n_implausible,
                "n_inconclusive": self.n_inconclusive,
                "n_unverifiable": self.n_unverifiable,
                "n_not_assessed": self.n_not_assessed,
                "posture": self.posture,
                "integrity_ok": self.integrity_ok,
            }
        )


# ---------------------------------------------------------------------------
# Audit event builder
# ---------------------------------------------------------------------------


def ai_counterfactual_audit_event(
    audit_kind: str, seq: int, **details: Any
) -> Dict[str, Any]:
    """Build one ``audit.ndjson/1`` event row for the AI-counterfactual ledger."""
    if audit_kind not in AUDIT_KINDS:
        raise AuditKindError(f"unknown audit kind: {audit_kind!r}")
    if isinstance(seq, bool) or not isinstance(seq, int) or seq < 0:
        raise SeqOrderError("audit seq must be a non-negative int")
    for key in details:
        if key in _BANNED_AUDIT_KEYS:
            raise AuditKindError(f"banned raw key in audit detail: {key!r}")
    return {
        "schema": "audit.ndjson/1",
        "kind": audit_kind,
        "seq": seq,
        "details": dict(details),
    }


# ---------------------------------------------------------------------------
# Ledger
# ---------------------------------------------------------------------------


class AICounterfactual:
    """AI-counterfactual decision ledger, Simulated.

    ``counterfactual()`` / ``retire()`` mutate the ledger and consume
    caller seqs; ``verify()`` / ``evaluate()`` and the other views are
    pure reads.
    """

    def __init__(self) -> None:
        self._lock = threading.RLock()
        self._systems: Dict[str, List[str]] = {}
        self._counterfactuals: Dict[str, CounterfactualRecord] = {}
        self._counterfactuals_by_system: Dict[str, List[str]] = {}
        self._retired: Dict[str, RetireRecord] = {}
        self._cfn_counter = 0
        self._seq = 0
        self._audit: List[Dict[str, Any]] = []
        self._rejected = 0

    # -- internal helpers -------------------------------------------------

    def _check_seq(self, seq: Any) -> int:
        if isinstance(seq, bool) or not isinstance(seq, int) or seq < 1:
            raise SeqOrderError("seq must be a positive int, not bool")
        return seq

    def _claim_seq(self, seq: int) -> None:
        """Claim a strictly increasing seq; rewinds raise bare."""
        if seq <= self._seq:
            raise SeqOrderError(
                f"seq must be strictly increasing, got {seq} after {self._seq}"
            )
        self._seq = seq

    def _burn(self, seq: int, method: str, exc: AICounterfactualError) -> None:
        """Book a failed mutation: seq consumed, rejected row appended."""
        self._rejected += 1
        self._audit.append(
            ai_counterfactual_audit_event(
                "rejected",
                seq,
                method=method,
                error=type(exc).__name__,
                error_detail=str(exc),
            )
        )

    def _require_live_system(self, system_id: str) -> None:
        if system_id in self._retired:
            raise RetiredSystemError(f"system already retired: {system_id!r}")

    def _require_known_system(self, system_id: str) -> None:
        if system_id not in self._systems:
            raise UnknownSystemError(f"unknown system: {system_id!r}")

    # -- mutations --------------------------------------------------------

    def counterfactual(
        self,
        system_id: Any,
        seq: Any,
        generation_kind: Any = "input-perturbation",
        verdict: Any = "not-assessed",
        severity: Any = 0,
        counterfactual_digest: Any = "",
    ) -> CounterfactualRecord:
        """Book one declared counterfactual pair (minted ``cfn-N``).

        The first counterfactual registers its system. Severity is a
        host-reported int in [0, 100] booked as data. Raw originals,
        perturbations, feature vectors, and attribution internals
        travel as a digest pin only; they never enter records.
        """
        with self._lock:
            seq_v = self._check_seq(seq)
            self._claim_seq(seq_v)
            try:
                sid = _require_id(system_id, "system_id")
                if sid in self._retired:
                    raise RetiredSystemError(f"system id never recycled: {sid!r}")
                if not isinstance(generation_kind, str) or generation_kind not in GENERATION_KINDS:
                    raise BadGenerationKindError(
                        f"generation_kind must be one of {sorted(GENERATION_KINDS)}"
                    )
                if not isinstance(verdict, str) or verdict not in VERDICTS:
                    raise BadVerdictError(f"verdict must be one of {sorted(VERDICTS)}")
                sev = _require_severity(severity, "severity")
                pin = _require_digest(counterfactual_digest, "counterfactual_digest")
                self._cfn_counter += 1
                cid = f"cfn-{self._cfn_counter}"
                rec = CounterfactualRecord(
                    counterfactual_id=cid,
                    system_id=sid,
                    generation_kind=generation_kind,
                    verdict=verdict,
                    severity=sev,
                    counterfactual_digest=pin,
                    digest=_digest_pin(
                        {
                            "schema": SCHEMA_PIN,
                            "counterfactual_id": cid,
                            "system_id": sid,
                            "generation_kind": generation_kind,
                            "verdict": verdict,
                            "severity": sev,
                            "counterfactual_digest": pin,
                        }
                    ),
                )
                self._counterfactuals[cid] = rec
                self._systems.setdefault(sid, []).append(cid)
                self._counterfactuals_by_system.setdefault(sid, []).append(cid)
                self._audit.append(
                    ai_counterfactual_audit_event(
                        "counterfactualled",
                        seq_v,
                        counterfactual_id=cid,
                        system_id=sid,
                        generation_kind=generation_kind,
                        verdict=verdict,
                        severity=sev,
                    )
                )
                return rec
            except AICounterfactualError as exc:
                self._burn(seq_v, "counterfactual", exc)
                raise

    def retire(
        self,
        system_id: Any,
        seq: Any,
        reason: Any = "manual",
    ) -> RetireRecord:
        """Terminally retire a system id; ids are never recycled."""
        with self._lock:
            seq_v = self._check_seq(seq)
            self._claim_seq(seq_v)
            try:
                sid = _require_id(system_id, "system_id")
                if sid in self._retired:
                    raise RetiredSystemError(f"system already retired: {sid!r}")
                self._require_known_system(sid)
                if not isinstance(reason, str) or reason not in RETIRE_REASONS:
                    raise BadReasonError(
                        f"reason must be one of {sorted(RETIRE_REASONS)}"
                    )
                rec = RetireRecord(
                    system_id=sid,
                    reason=reason,
                    digest=_digest_pin(
                        {
                            "schema": SCHEMA_PIN,
                            "system_id": sid,
                            "reason": reason,
                        }
                    ),
                )
                self._retired[sid] = rec
                self._audit.append(
                    ai_counterfactual_audit_event(
                        "retired",
                        seq_v,
                        system_id=sid,
                        reason=reason,
                    )
                )
                return rec
            except AICounterfactualError as exc:
                self._burn(seq_v, "retire", exc)
                raise

    # -- pure-read views ---------------------------------------------------

    def counterfactual_record(self, counterfactual_id: Any, seq: Any) -> CounterfactualRecord:
        """Return one counterfactual record (pure read)."""
        with self._lock:
            self._check_seq(seq)
            cid = _require_id(counterfactual_id, "counterfactual_id")
            if cid not in self._counterfactuals:
                raise UnknownCounterfactualError(f"unknown counterfactual: {cid!r}")
            return self._counterfactuals[cid]

    def system_ids(self, seq: Any) -> Tuple[str, ...]:
        """All registered system ids in registration order."""
        with self._lock:
            self._check_seq(seq)
            return tuple(self._systems.keys())

    def counterfactual_ids(self, seq: Any) -> Tuple[str, ...]:
        """All counterfactual ids in mint order."""
        with self._lock:
            self._check_seq(seq)
            return tuple(f"cfn-{i}" for i in range(1, self._cfn_counter + 1))

    def counterfactuals_for(self, system_id: Any, seq: Any) -> Tuple[str, ...]:
        """Counterfactual ids booked against one system (mint order)."""
        with self._lock:
            self._check_seq(seq)
            sid = _require_id(system_id, "system_id")
            self._require_known_system(sid)
            return tuple(self._counterfactuals_by_system[sid])

    def retired_ids(self, seq: Any) -> Tuple[str, ...]:
        """All retired system ids."""
        with self._lock:
            self._check_seq(seq)
            return tuple(self._retired.keys())

    def evaluate(self, system_id: Any, seq: Any) -> EvaluationReport:
        """Per-system plausibility tallies and ledger-rule posture (pure read).

        Posture as data: ``unexamined`` (no counterfactuals) ->
        ``implausible`` (any implausible) -> ``contested`` (any
        inconclusive or unverifiable) -> ``unassessed`` (any
        not-assessed) -> ``covered`` (all plausible). ``integrity_ok``
        re-derives every in-scope digest pin as data.
        """
        with self._lock:
            self._check_seq(seq)
            sid = _require_id(system_id, "system_id")
            self._require_known_system(sid)
            cfn_ids = self._counterfactuals_by_system.get(sid, ())
            n_plausible = n_implausible = n_inconclusive = 0
            n_unverifiable = n_not_assessed = 0
            for cid in cfn_ids:
                verdict = self._counterfactuals[cid].verdict
                if verdict == "plausible":
                    n_plausible += 1
                elif verdict == "implausible":
                    n_implausible += 1
                elif verdict == "inconclusive":
                    n_inconclusive += 1
                elif verdict == "unverifiable":
                    n_unverifiable += 1
                else:
                    n_not_assessed += 1
            if not cfn_ids:
                posture = "unexamined"
            elif n_implausible > 0:
                posture = "implausible"
            elif n_inconclusive > 0 or n_unverifiable > 0:
                posture = "contested"
            elif n_not_assessed > 0:
                posture = "unassessed"
            else:
                posture = "covered"
            integrity_ok = all(
                self._counterfactuals[cid].verify() for cid in cfn_ids
            )
            return EvaluationReport(
                system_id=sid,
                n_counterfactuals=len(cfn_ids),
                n_plausible=n_plausible,
                n_implausible=n_implausible,
                n_inconclusive=n_inconclusive,
                n_unverifiable=n_unverifiable,
                n_not_assessed=n_not_assessed,
                posture=posture,
                integrity_ok=integrity_ok,
                digest=_digest_pin(
                    {
                        "schema": SCHEMA_PIN,
                        "system_id": sid,
                        "n_counterfactuals": len(cfn_ids),
                        "n_plausible": n_plausible,
                        "n_implausible": n_implausible,
                        "n_inconclusive": n_inconclusive,
                        "n_unverifiable": n_unverifiable,
                        "n_not_assessed": n_not_assessed,
                        "posture": posture,
                        "integrity_ok": integrity_ok,
                    }
                ),
            )

    def verify(self, record_id: Any, seq: Any) -> VerificationReport:
        """Re-derive one counterfactual record's digest pin (pure read).

        Seq shape validated only, never consumed, no audit row.
        Verdict ``verified`` / ``tampered`` booked as data; tamper is
        reported, never raised.
        """
        with self._lock:
            self._check_seq(seq)
            rid = _require_id(record_id, "record_id")
            if rid in self._counterfactuals:
                rec = self._counterfactuals[rid]
                kind = "counterfactual"
            else:
                raise UnknownCounterfactualError(f"unknown record: {rid!r}")
            verdict = "verified" if rec.verify() else "tampered"
            return VerificationReport(
                record_id=rid,
                record_kind=kind,
                verdict=verdict,
                digest=_digest_pin(
                    {
                        "schema": SCHEMA_PIN,
                        "record_id": rid,
                        "record_kind": kind,
                        "verdict": verdict,
                    }
                ),
            )

    def audit_log(self, seq: Any) -> Tuple[Dict[str, Any], ...]:
        """All audit rows so far (pure read)."""
        with self._lock:
            self._check_seq(seq)
            return tuple(self._audit)

    def stats(self, seq: Any) -> Dict[str, int]:
        """Ledger counters (pure read)."""
        with self._lock:
            self._check_seq(seq)
            return {
                "systems": len(self._systems),
                "counterfactuals": len(self._counterfactuals),
                "retired": len(self._retired),
                "rejected": self._rejected,
            }

    @staticmethod
    def stdlib_only() -> bool:
        """AST self-check: only stdlib imports (+ the in-repo sibling)."""
        import ast as _ast
        import pathlib as _pathlib

        allowed = {
            "__future__",
            "threading",
            "dataclasses",
            "hashlib",
            "json",
            "typing",
            "canonical_json",
            "ast",
            "pathlib",
        }
        tree = _ast.parse(_pathlib.Path(__file__).read_text())
        for node in _ast.walk(tree):
            if isinstance(node, _ast.Import):
                for a in node.names:
                    if a.name.split(".")[0] not in allowed:
                        return False
            elif isinstance(node, _ast.ImportFrom) and node.module:
                if node.module.split(".")[0] not in allowed:
                    return False
        return True


def main() -> None:
    """Self-check: exercise the ledger end to end."""
    ac = AICounterfactual()
    pin = "sha256:" + "ab" * 32
    rec = ac.counterfactual(
        "sys-1",
        1,
        generation_kind="input-perturbation",
        verdict="plausible",
        severity=10,
        counterfactual_digest=pin,
    )
    assert rec.counterfactual_id == "cfn-1"
    assert rec.verify()
    rep = ac.evaluate("sys-1", 2)
    assert rep.verify()
    assert rep.posture == "covered"
    assert rep.integrity_ok is True
    vrf = ac.verify("cfn-1", 3)
    assert vrf.verify()
    assert vrf.verdict == "verified"
    rtr = ac.retire("sys-1", 4, reason="decommissioned")
    assert rtr.verify()
    assert ac.stats(5) == {
        "systems": 1,
        "counterfactuals": 1,
        "retired": 1,
        "rejected": 0,
    }
    print("ai-counterfactual OK: counterfactual, verify, evaluate, retire, pins, audit")


if __name__ == "__main__":
    main()
